# This file was generated by GoReleaser. DO NOT EDIT.
cask "note-cli" do
  version "1.12.2"

  on_macos do
    on_intel do
      sha256 "0bc659e10e79f9580dd0d2fb0f9093e744121c46927ebc5310dc797fc280dd04"
      url "https://github.com/blues/note-cli/releases/download/v#{version}/note-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9627f2c8874240ba510f00d068c80b61ab5d1e5c5f4226c6df59760c8044c455"
      url "https://github.com/blues/note-cli/releases/download/v#{version}/note-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9831534ef1f0b5450cb58e442c648657252db08f89ce43bf912e66582691d9e0"
      url "https://github.com/blues/note-cli/releases/download/v#{version}/note-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7f78c8effaa88ce66afdbedec55ea8211626a071d57dea9d3f3c19822f2dc0a9"
      url "https://github.com/blues/note-cli/releases/download/v#{version}/note-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "note-cli"
  desc "Note CLI"
  homepage "https://blues.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notecard"
  binary "notehub"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notecard"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notehub"]
    end
  end

  # No zap stanza required

end
