# This file was generated by GoReleaser. DO NOT EDIT.
cask "note-cli" do
  name "note-cli"
  desc "Note CLI"
  homepage "https://blues.com"
  version "1.9.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notecard"
  binary "notehub"

  on_macos do
    on_intel do
      url "https://github.com/blues/note-cli/releases/download/v#{version}/note-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "d15bf268f4f73df60c0534a56d98db2a6cd4f12a102a31c72aa69e2b4e0185fd"
    end
    on_arm do
      url "https://github.com/blues/note-cli/releases/download/v#{version}/note-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "de3e4e47032edbee2b229968391b4688643efd77e9f4aa2cebf5ce314e00c688"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/blues/note-cli/releases/download/v#{version}/note-cli_#{version}_linux_amd64.tar.gz"
      sha256 "6d88fd71a9546f10b8162c919334e1e1efd085242455d60bff203f3aa5060795"
    end
    on_arm do
      url "https://github.com/blues/note-cli/releases/download/v#{version}/note-cli_#{version}_linux_arm64.tar.gz"
      sha256 "bdca41a7f1109d50b873d4be93502802c6d3b171df34ab53d59c41eed3453120"
    end
  end

  # No zap stanza required
end
