# This file was generated by GoReleaser. DO NOT EDIT.
cask "note-cli" do
  version "1.10.1"

  on_macos do
    on_intel do
      sha256 "27d41b81b3f2edbefe27a97f9c24c3284799aeb5ac1c6a6bd52bc344397d332e"
      url "https://github.com/blues/note-cli/releases/download/v#{version}/note-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b32e0e4d002268b8185f485e10ec7bebc64218f55115811afab433fa623b6198"
      url "https://github.com/blues/note-cli/releases/download/v#{version}/note-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "45465d572649c63cd6fbdb8af9d00be1089368cf325a66aeb7bdf86cfb3ea727"
      url "https://github.com/blues/note-cli/releases/download/v#{version}/note-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "596058baf38f0c0ad1a76eb52e8a12087c9d3db09dbea468b68d55a70f007b4d"
      url "https://github.com/blues/note-cli/releases/download/v#{version}/note-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "note-cli"
  desc "Note CLI"
  homepage "https://blues.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notecard"
  binary "notehub"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notecard"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notehub"]
    end
  end

  # No zap stanza required

end
