# This file was generated by GoReleaser. DO NOT EDIT.
cask "note-cli" do
  name "note-cli"
  desc "Note CLI"
  homepage "https://blues.com"
  version "1.9.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "note-cli"

  on_macos do
    on_intel do
      url "https://github.com/blues/note-cli/releases/download/v#{version}/note-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "0eeabb6d5861dbe2179883624296949ae59d4ff6e525e1cde8a5e34055487266"
    end
    on_arm do
      url "https://github.com/blues/note-cli/releases/download/v#{version}/note-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "219a3e018c087407f240dc608a50aba62b95edd46a8a243c35bdf4abcee650ea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/blues/note-cli/releases/download/v#{version}/note-cli_#{version}_linux_amd64.tar.gz"
      sha256 "25a3dc2e3070823f196ce5fba065eff23b9b1418b294c10f60fc7ba71ae2c8cc"
    end
    on_arm do
      url "https://github.com/blues/note-cli/releases/download/v#{version}/note-cli_#{version}_linux_arm64.tar.gz"
      sha256 "39ffd2a9edc624874dbcd59c058d766bfecac584a352fd521a176b8767478b35"
    end
  end

  # No zap stanza required
end
