# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NoteCli < Formula
  desc "Note CLI"
  homepage "https://blues.com"
  version "1.7.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blues/note-cli/releases/download/v1.7.4/note-cli_1.7.4_darwin_amd64.tar.gz"
      sha256 "50132a9f3ce50e12969efe895bc01b3ecf446f16efeea26ec39425a18fbd7f0d"

      def install
        bin.install "notecard"
        bin.install "notehub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blues/note-cli/releases/download/v1.7.4/note-cli_1.7.4_darwin_arm64.tar.gz"
      sha256 "aea80f77a4f97b5f8764389c902a589ad6125151f361e837af1361cfb2ccffcf"

      def install
        bin.install "notecard"
        bin.install "notehub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/blues/note-cli/releases/download/v1.7.4/note-cli_1.7.4_linux_amd64.tar.gz"
      sha256 "7fb39d0074b0ea9cba779e394851149473e1729187e404081d7108377769c957"
      def install
        bin.install "notecard"
        bin.install "notehub"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/blues/note-cli/releases/download/v1.7.4/note-cli_1.7.4_linux_armv6.tar.gz"
      sha256 "7485af87b9abd3af4b433204297eeea3dc74a5d1cffe007cb8b15b4bc427ed8b"
      def install
        bin.install "notecard"
        bin.install "notehub"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/blues/note-cli/releases/download/v1.7.4/note-cli_1.7.4_linux_arm64.tar.gz"
      sha256 "3debb1a54b14beadf5df14583946c4c66b33b8d640de6839770646c0c1fe7a54"
      def install
        bin.install "notecard"
        bin.install "notehub"
      end
    end
  end
end
